In [1]:
import pandas as pd
import numpy as np

In [2]:
# import data
# fetch_20newsgroups dataset

In [4]:
import sklearn.datasets as skd
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
news_train = skd.load_files('C:/Users/lenovo/Desktop/text classification data/20news-bydate-train', categories= categories, encoding= 'ISO-8859-1')
news_test = skd.load_files('C:/Users/lenovo/Desktop/text classification data/20news-bydate-test',categories= categories, encoding= 'ISO-8859-1')

In [43]:
# news_train

In [7]:
print(news_train.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [8]:
news_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [9]:
# count vectorizer
# count the number of occurences of words in the documents

In [11]:
# fit method is used to give a unique number
# transform method is used to count the number

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
text = ['The quick brown fox jumped over the  lazy dog.', 'The dog', 'The fox']
vector = CountVectorizer()
vector.fit(text)
print("Print Vocabulary: "+str(vector.get_feature_names())+'\n\n')

counts = vector.transform(text)
print("The shape of count is "+str(counts.shape)+'\n\n')
print("Printing count: "+'\n'+str(counts.toarray()))

Print Vocabulary: ['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']


The shape of count is (3, 8)


Printing count: 
[[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]


In [16]:
count_vect = CountVectorizer()
x_train_tf = count_vect.fit_transform(news_train.data)
print(x_train_tf.shape)
# 35788 features
# 2257 docs

(2257, 35788)


In [17]:
# inverse document frquency
# downscales words which appear a lot of times within the documents

In [18]:
from sklearn.feature_extraction.text import TfidfTransformer
vectorizer = TfidfTransformer()

vectorizer.fit(counts)
print("Learning frequency of all the features: "+str(vectorizer.idf_)+'\n\n')

freq = vectorizer.transform(counts)
print('Transforming the matrix based on the learnt frequencies or weight:\n\n'+str(freq.toarray()))


Learning frequency of all the features: [1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


Transforming the matrix based on the learnt frequencies or weight:

[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]
 [0.         0.78980693 0.         0.         0.         0.
  0.         0.61335554]
 [0.         0.         0.78980693 0.         0.         0.
  0.         0.61335554]]


In [20]:
tfidfTransformer = TfidfTransformer()
x_train_tfidf = tfidfTransformer.fit_transform(x_train_tf)
x_train_tfidf.shape

(2257, 35788)

In [21]:
# MultinomialNB
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train_tfidf, news_train.target)

In [24]:
docs_new =['God is love', 'OpenGl on the GPU is fast']
x_new_counts = count_vect.transform(docs_new)
x_new_tfidf = tfidfTransformer.transform(x_new_counts)
predicted = clf.predict(x_new_tfidf)

In [26]:
for x in predicted:
    print(x)

3
1


In [28]:
news_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [31]:
x_test_tf = count_vect.transform(news_test.data)
x_test_tfidf = tfidfTransformer.transform(x_test_tf)
predicted = clf.predict(x_test_tfidf)

In [41]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(news_test.target, predicted))
print(metrics.classification_report(news_test.target, predicted, target_names = news_test.target_names))
print("Confusion Matrix: "+"\n",metrics.confusion_matrix(news_test.target, predicted))

Accuracy:  0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

           avg / total       0.88      0.83      0.84      1502

Confusion Matrix: 
 [[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]
