In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import nltk

In [2]:
df = pd.read_csv('twitter_x_y_train.csv')
df

tweet_id airline_sentiment     airline  \
0      567900433542488064          negative   Southwest   
1      569989168903819264          positive   Southwest   
2      568089179520954368          positive      United   
3      568928195581513728          negative   Southwest   
4      568594180014014464          negative      United   
5      569677636613439488          negative      United   
6      569658903044218880          negative       Delta   
7      568542766860541952          positive       Delta   
8      570116209263427584          negative      United   
9      568870144891600896          positive   Southwest   
10     567793635892174848          negative   Southwest   
11     569879497891303424           neutral       Delta   
12     568517827482685440          positive  US Airways   
13     568212893012860928          negative   Southwest   
14     569270187725160449          negative  US Airways   
15     567816651900583936          negative  US Airways   
16     569690131235340288          negative    American   
17     569932678688055296          negative       Delta   
18     569939494465462272          negative       Delta   
19     569958224968982528          negative    American   
20     568361346464497664          negative  US Airways   
21     568126682336534529           neutral   Southwest   
22     568883826333777920          negative  US Airways   
23     570055700790931456          negative      United   
24     568804026789138433          positive      United   
25     567925054853496832           neutral      United   
26     568434301496381441          negative       Delta   
27     570083397873373184          negative      United   
28     568585356586586113          positive   Southwest   
29     570022265343123456          positive    American   
...                   ...               ...         ...   
10950  569125697530101760          positive       Delta   
10951  569682747712770048          negative   Southwest   
10952  569372333267394560          negative   Southwest   
10953  569333972452265985          negative      United   
10954  568426579874996224          negative   Southwest   
10955  570018254271463424          negative       Delta   
10956  568118177537744897           neutral   Southwest   
10957  568522861205266432          negative  US Airways   
10958  570290993339244547          negative      United   
10959  569624009354170369          negative  US Airways   
10960  568841631585021952          negative      United   
10961  569262534232039427          negative       Delta   
10962  569308255966666753           neutral      United   
10963  569369008580874240          negative  US Airways   
10964  569008708174262272          negative      United   
10965  570164810144481280           neutral      United   
10966  568417151176060929          negative      United   
10967  567617081336950784          negative   Southwest   
10968  569664787946164224          negative    American   
10969  568531020267458561          positive   Southwest   
10970  570283248301043712          negative   Southwest   
10971  569087442092826624           neutral       Delta   
10972  570051488875020288          negative  US Airways   
10973  569676702030262272          negative    American   
10974  569676404893163520          positive   Southwest   
10975  569934458364813313           neutral    American   
10976  568564006329434113          positive      United   
10977  569643648910028801          negative  US Airways   
10978  568864981917110272          negative  US Airways   
10979  568929299350179840          negative      United   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN    ColeyGirouard                 NaN   
1                        NaN    WalterFaddoul                 NaN   
2                        NaN        LocalKyle                 NaN   
3                        NaN      amccarthy19                 NaN   
4            

In [3]:
df.columns

Index(['tweet_id', 'airline_sentiment', 'airline', 'airline_sentiment_gold',
       'name', 'negativereason_gold', 'retweet_count', 'text', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'],
      dtype='object')

In [4]:
del df['tweet_id']

In [5]:
df.isnull().sum()

airline_sentiment             0
airline                       0
airline_sentiment_gold    10949
name                          0
negativereason_gold       10956
retweet_count                 0
text                          0
tweet_coord               10204
tweet_created                 0
tweet_location             3550
user_timezone              3577
dtype: int64

In [6]:
df.shape

(10980, 11)

In [7]:
df.drop(['airline_sentiment_gold', 'negativereason_gold', 'tweet_coord'], axis = 1, inplace = True)

In [8]:
df.columns

Index(['airline_sentiment', 'airline', 'name', 'retweet_count', 'text',
       'tweet_created', 'tweet_location', 'user_timezone'],
      dtype='object')

In [9]:
df.shape

(10980, 8)

In [10]:
df.isnull().sum()

airline_sentiment       0
airline                 0
name                    0
retweet_count           0
text                    0
tweet_created           0
tweet_location       3550
user_timezone        3577
dtype: int64

In [11]:
df.drop(['tweet_location', 'user_timezone'], axis = 1, inplace = True)

In [12]:
df.columns

Index(['airline_sentiment', 'airline', 'name', 'retweet_count', 'text',
       'tweet_created'],
      dtype='object')

In [13]:
df.dtypes

airline_sentiment    object
airline              object
name                 object
retweet_count         int64
text                 object
tweet_created        object
dtype: object

In [14]:
df.drop(['name', 'tweet_created'], axis = 1, inplace = True)

In [15]:
df.columns

Index(['airline_sentiment', 'airline', 'retweet_count', 'text'], dtype='object')

In [16]:
df.retweet_count.unique()

array([ 0,  1, 22,  2,  3,  4,  7,  5, 18,  6, 28,  8, 44, 31, 15],
      dtype=int64)

In [17]:
airlines = []
for i in range(df.shape[0]):
    airlines.append(df.iloc[i]['airline'].lower())
airlines =set(airlines)

In [18]:
airlines

{'american', 'delta', 'southwest', 'united', 'us airways', 'virgin america'}

In [19]:
df.drop(['retweet_count', 'airline'], axis = 1, inplace = True)

In [20]:
df.columns

Index(['airline_sentiment', 'text'], dtype='object')

In [21]:
x = df.iloc[:, 1]
y = df.iloc[:, 0]

In [22]:
import string
from nltk.corpus import stopwords
stops = stopwords.words("english")
stops = stops + list(string.punctuation)

In [23]:
from nltk.tokenize import word_tokenize

In [24]:
s = "the sky is blue"
word_tokenize(s)

['the', 'sky', 'is', 'blue']

In [25]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [26]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [27]:
from nltk import pos_tag

In [28]:
word = "nice"
pos_tag([word])
get_simple_pos(pos_tag([word])[0][1])

'a'

In [29]:
for i in range(len(x)):
    tweet = x.iloc[i]
    words = word_tokenize(tweet)
    cleaned_words = []
    for word in words:
        if word.lower() not in stops and word.lower() not in airlines:
            cleaned_word = lemmatizer.lemmatize(word, pos = get_simple_pos(pos_tag([word])[0][1]))
            cleaned_words.append(cleaned_word)
    tweet = " ".join(cleaned_words)
    x.iloc[i] = tweet

In [30]:
# you may make a set of the airline column and remove the names of the airlines from the tweet to avoid the model from getting cluttered

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0, test_size = 0.3)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
count_vec = CountVectorizer(max_features = 2000, ngram_range = (1, 2))
x_train_features = count_vec.fit_transform(x_train)
x_train_features

<7686x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 72227 stored elements in Compressed Sparse Row format>

In [33]:
x_train_features.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
count_vec.get_feature_names()

['000',
 '10',
 '10 hour',
 '10 min',
 '10 minute',
 '100',
 '10pm',
 '11',
 '12',
 '12 hour',
 '13',
 '130',
 '14',
 '15',
 '15 min',
 '15 minute',
 '150',
 '16',
 '17',
 '18',
 '19',
 '1hr',
 '1k',
 '1st',
 '1st class',
 '20',
 '20 min',
 '20 minute',
 '200',
 '2015',
 '21',
 '22',
 '23',
 '24',
 '24 hour',
 '24 hr',
 '25',
 '25 min',
 '26',
 '27',
 '28',
 '2day',
 '2hrs',
 '2nd',
 '2x',
 '30',
 '30 flight',
 '30 min',
 '30 minute',
 '300',
 '32',
 '35',
 '3rd',
 '40',
 '40 min',
 '40 minute',
 '400',
 '45',
 '45 min',
 '45 minute',
 '48',
 '4th',
 '50',
 '500',
 '60',
 '70',
 '700',
 '728',
 '75',
 '80',
 '800',
 '800 number',
 '90',
 '90 min',
 'a320',
 'aa',
 'able',
 'able get',
 'absolute',
 'absolutely',
 'absurd',
 'accept',
 'acceptable',
 'access',
 'accommodate',
 'account',
 'acct',
 'act',
 'action',
 'actual',
 'actually',
 'add',
 'additional',
 'address',
 'advantage',
 'advice',
 'advise',
 'advisory',
 'afford',
 'afternoon',
 'age',
 'agent',
 'agent help',
 'agent 

In [35]:
x_test_features = count_vec.transform(x_test)

In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [37]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(x_train_features, y_train)
y_pred = clf.predict(x_test_features)

In [38]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6287188828172434
[[2071    0    0]
 [ 683    0    0]
 [ 540    0    0]]
             precision    recall  f1-score   support

   negative       0.63      1.00      0.77      2071
    neutral       0.00      0.00      0.00       683
   positive       0.00      0.00      0.00       540

avg / total       0.40      0.63      0.49      3294



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(x_train_features, y_train)
y_pred = clf.predict(x_test_features)

In [40]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7270795385549484
[[1794  187   90]
 [ 281  324   78]
 [ 173   90  277]]
             precision    recall  f1-score   support

   negative       0.80      0.87      0.83      2071
    neutral       0.54      0.47      0.50       683
   positive       0.62      0.51      0.56       540

avg / total       0.72      0.73      0.72      3294



In [41]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x_train_features, y_train)
y_pred = clf.predict(x_test_features)

In [42]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6739526411657559
[[1588  342  141]
 [ 251  346   86]
 [ 128  126  286]]
             precision    recall  f1-score   support

   negative       0.81      0.77      0.79      2071
    neutral       0.43      0.51      0.46       683
   positive       0.56      0.53      0.54       540

avg / total       0.69      0.67      0.68      3294



In [43]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train_features.todense(), y_train)
y_pred = clf.predict(x_test_features.todense())

In [44]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.47146326654523374
[[955 530 586]
 [ 67 191 425]
 [ 66  67 407]]
             precision    recall  f1-score   support

   negative       0.88      0.46      0.60      2071
    neutral       0.24      0.28      0.26       683
   positive       0.29      0.75      0.42       540

avg / total       0.65      0.47      0.50      3294



In [45]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train_features.todense(), y_train)
y_pred = clf.predict(x_test_features.todense())

In [46]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7738312082574378
[[1861  160   50]
 [ 251  362   70]
 [ 138   76  326]]
             precision    recall  f1-score   support

   negative       0.83      0.90      0.86      2071
    neutral       0.61      0.53      0.57       683
   positive       0.73      0.60      0.66       540

avg / total       0.77      0.77      0.77      3294



In [47]:
# the tweets are getting wrongly classified as negative as evident from the confusion_matrix as the support for the negative tweets is too much as compared to that of the other tweets

In [48]:
y.unique()

array(['negative', 'positive', 'neutral'], dtype=object)

In [49]:
x_train_features.shape

(7686, 2000)

In [50]:
# dividing training set into 3 sets and will then use majority of the prediction

In [51]:
x_train_batches = []
y_train_batches = []
N = x_train_features.shape[0]
start = 0
end = int(N/3)
for j in range(3):
    x_train_batches.append(x_train_features[start: end, :])
    y_train_batches.append(y_train[start: end])
    start = end
    end = int(end + N/3)

In [52]:
y_pred_batches = []
for j in range(3):
    clf = LogisticRegression()
    clf.fit(x_train_batches[j], y_train_batches[j])
    y_pred_batches.append(clf.predict(x_test_features))

In [53]:
y_pred = []
for i in range(len(x_test_features.todense())):
    neg = 0
    pos = 0
    neu = 0
    for j in range(3):
        if y_pred_batches[j][i] == 'negative':
            neg += 1
        elif y_pred_batches[j][i] == 'positive':
            pos += 1
        else:
            neu += 1
    if pos >= neg and pos >= neu:
        y_pred.append('positive')
    elif neg >= pos and neg >= neu:
        y_pred.append('negative')
    else:
        y_pred.append('neutral')

In [54]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7622950819672131
[[1879  122   70]
 [ 290  317   76]
 [ 155   70  315]]
             precision    recall  f1-score   support

   negative       0.81      0.91      0.86      2071
    neutral       0.62      0.46      0.53       683
   positive       0.68      0.58      0.63       540

avg / total       0.75      0.76      0.75      3294

